package com.dineflow.constant;

/** 稳定的接口错误标识；中文提示可调整，客户端只按这些标识分支。 */
public enum BusinessErrorCode {
    INVALID_PARAMETER, USER_NOT_LOGIN, CART_CHANGED, ADDRESS_CHANGED, PRICE_CHANGED,
    ITEM_CHANGED, ITEM_NOT_AVAILABLE, INVALID_CART_ITEM, SHOP_CLOSED,
    INVALID_SETTLEMENT, SETTLEMENT_EXPIRED, MAP_SERVICE_UNAVAILABLE, DELIVERY_OUT_OF_RANGE,
    BUSINESS_ERROR
}
