server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${dineflow.datasource.driver-class-name}
    url: jdbc:mysql://${dineflow.datasource.host}:${dineflow.datasource.port}/${dineflow.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${dineflow.datasource.username}
    password: ${dineflow.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: ${dineflow.redis.host}
    port: ${dineflow.redis.port}
    password: ${dineflow.redis.password}
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间

# mybatis-plus 配置
mybatis-plus:
  # Mapper.xml 文件地址，默认值
  mapper-locations: classpath:mapper/*.xml
  # 扫描包别名，扫描实体类
  type-aliases-package: com.dineflow.entity
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    # 开启二级缓存
    cache-enabled: false
  global-config:
    db-config:
      # 主键自增
      id-type: auto
      # 更新策略，只更新非空字段
      update-strategy: not_null

# 日志配置
logging:
  level:
    com:
      dineflow:
        mapper: debug
        service: info
        controller: info

dineflow:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${dineflow.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${dineflow.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: ${dineflow.jwt.user-secret-key}
    user-ttl: ${dineflow.jwt.user-ttl}
    user-token-name: authentication
  alioss:
    endpoint: ${dineflow.alioss.endpoint}
    bucket-name: ${dineflow.alioss.bucket-name}
    region: ${dineflow.alioss.region}
  wechat:
    appid: ${dineflow.wechat.appid}
    secret: ${dineflow.wechat.secret}
    pay:
      # 根据这个值决定要不要加载微信支付配置类
      enabled: false
    # 微信支付商户号
    mchid: ${dineflow.wechat.mchid}
    # 商户 API 证书的序列号
    mch-serial-no: ${dineflow.wechat.mch-serial-no}
    # 商户私钥文件（存储在本地）
    private-key-file-path: ${dineflow.wechat.private-key-file-path}
    # APIv3 对称密钥，用于回调解密等（自己在平台设置）
    api-v3-key: ${dineflow.wechat.api-v3-key}
    # 微信支付公钥 pem 文件（存储在本地）
    public-key-file-path: ${dineflow.wechat.public-key-file-path}
    # 微信支付公钥 ID
    public-key-id: ${dineflow.wechat.public-key-id}
    # 支付结果回调到服务器的 URL
    notifyUrl: ${dineflow.wechat.notifyUrl}
    # 退款结果回调到你服务器的 URL
    refundNotifyUrl: ${dineflow.wechat.refundNotifyUrl}
